# Generated by Django 2.2.24 on 2021-09-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fotografia',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
